#!/usr/bin/env python3
"""Parse NME 04 Cyberware.md into CyberwareCatalog.generated.js for the combat app."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CYBERWARE_MD = ROOT / "source/Source Text/Night Market Encyclopedia/04 Cyberware.md"
OUT_JS = Path(__file__).resolve().parents[1] / "js/data/CyberwareCatalog.generated.js"

SKIP_SECTIONS = {"CEMK Cyberware", "Contents"}


def slugify(name: str) -> str:
    s = name.strip("*").lower()
    s = re.sub(r"[®™]", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")[:80]


def parse_price_eb(cost: str) -> int:
    m = re.search(r"([\d,]+)\s*eb", cost, re.I)
    return int(m.group(1).replace(",", "")) if m else 0


def parse_row(cols: list[str], section: str) -> dict | None:
    if len(cols) < 8 or "eb" not in cols[1]:
        return None
    name = cols[0].strip()
    if name == "Name":
        return None

    cost = cols[1]
    install = cols[2]
    humanity_loss = cols[3]
    slots = cols[4]
    effect = cols[5]
    special = cols[6] if len(cols) > 6 else ""
    source = cols[7] if len(cols) > 7 else ""

    detail_parts = [install, humanity_loss]
    if slots and slots not in ("—", "-"):
        detail_parts.append(f"Slots {slots}")
    detail = " · ".join(p for p in detail_parts if p and p not in ("—", "-"))

    entry = {
        "id": slugify(name),
        "name": name.strip("*"),
        "kind": "cyberware",
        "source": f"NME 04 · {section}",
        "cost": cost,
        "priceEb": parse_price_eb(cost),
        "detail": detail or effect[:80],
        "cyberwareCategory": section,
        "install": install,
        "humanityLoss": humanity_loss,
        "slots": slots,
        "effect": effect,
    }
    if special and special not in ("—", "-"):
        entry["specialMechanisms"] = special
    if effect:
        entry["effectSummary"] = effect[:160]
    return entry


def main() -> None:
    text = CYBERWARE_MD.read_text(encoding="utf-8")
    by_id: dict[str, dict] = {}
    current: str | None = None

    for line in text.splitlines():
        if line.startswith("## ") and not line.startswith("## Contents"):
            current = line[3:].strip()
            continue
        if not current or current in SKIP_SECTIONS:
            continue
        if not line.startswith("| ") or line.startswith("|------"):
            continue

        cols = [c.strip() for c in line.strip().strip("|").split("|")]
        entry = parse_row(cols, current)
        if not entry:
            continue

        eid = entry["id"]
        if eid in by_id:
            existing = by_id[eid]
            cats = set(existing.get("categories") or [existing["cyberwareCategory"]])
            cats.add(current)
            entry = {**existing, **entry, "categories": sorted(cats)}
        else:
            entry["categories"] = [current]
        by_id[eid] = entry

    items = sorted(by_id.values(), key=lambda e: (e["cyberwareCategory"], e["name"].lower()))
    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text(
        "/** Auto-generated by scripts/build_cyberware_catalog.py — do not edit by hand. */\n"
        f"export const GENERATED_CYBERWARE_CATALOG = {json.dumps(items, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(items)} cyberware entries to {OUT_JS}")


if __name__ == "__main__":
    main()
